# Default values for gitlab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: gitlab/gitlab-ce
  tag: latest
  pullPolicy: IfNotPresent

sshPort: 22

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true

  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 30Gi

  gitlab_data:
    subPath: data
    mountPath: /var/opt/gitlab
  gitlab_config:
    subPath: config
    mountPath: /etc/gitlab
  gitlab_logs:
    subPath: logs
    mountPath: /var/log/gitlab

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
