#
# Configuration file for deploying the renku chart on minikube
#

global:
  renku:
    domain: renku-k8s.build

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: false
  hosts:
  - "renku-k8s.build"

jupyterhub:
  rbac:
    enabled: true
  hub:
    cookieSecret: 7c232b97bda321be7e59b9834dfadbb89652da1e0150dff9b3dadb9aa8b4caab
    baseUrl: '/jupyterhub/'
    extraEnv:
      GITLAB_HOST: http://gitlab.renku-k8s.build
  proxy:
    secretToken: f89ddee5ba10f2268fcefcd4e353235c255493095cd65addf29ebebf8df86255
  auth:
    state:
      enabled: true
      cryptoKey: 86282f03d9886a64a46ee38f946e9ee27a600df4559584eeb90d0bfbd5a3dc0e

gitlab:
  sshPort: 2222

ui:
  gitlabUrl: gitlab.renku-k8s.build
  jupyterhubUrl: http://renku-k8s.build/jupyterhub

notebooks:
  jupyterhub_base_url: /jupyterhub/
  jupyterhub_api_token: notebookstoken

runner:
  enabled: true
