---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gitlab.fullname" . }}
  labels:
    app: {{ template "gitlab.name" . }}
    chart: {{ template "gitlab.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.password }}
  gitlab-password: {{ .Values.password | b64enc | quote }}
{{- else }}
  gitlab-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}

{{- if .Values.global.gitlab.postgresPassword }}
  postgres-password: {{ .Values.global.gitlab.postgresPassword | b64enc | quote }}
{{- else }}
  postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}

{{- if .Values.global.gitlab.clientSecret }}
  gitlab-client-secret: {{ .Values.global.gitlab.clientSecret | b64enc | quote }}
{{- else }}
  gitlab-client-secret: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}

  shared-runners-registration-token: {{ .Values.sharedRunnersRegistrationToken | b64enc | quote }}
