apiVersion: v1
kind: Service
metadata:
  name: hub
spec:
  type: {{ .Values.hub.service.type }}
  {{ if .Values.hub.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.hub.service.loadBalancerIP }}
  {{- end }}
  selector:
    name: hub
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: hub
    - protocol: TCP
      port: 9080
      targetPort: 9080
      name: projects
